#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u "$UID" -x polybar >/dev/null; do sleep 1; done

# Launch top bar
for m in $(polybar --list-monitors | cut -d":" -f1); do
	bar='primary'

	if [[ "$m" != 'eDP1' ]]; then
		bar='aux'
	fi

	MONITOR="$m" polybar --reload "$bar" &
done
