#!/bin/bash

pkgs=(
	vim				# editor
	beets				# music organiser
	dunst				# notification manager
	i3-wm				# tilling window manager
	polybar				# status bar
	cmus				# music player
	rofi				# dmenu replacement
	termite				# terminal emulator
	picom				# compositor
	nnn				# terminal file manager
	adobe-source-code-pro-fonts	# main font
	volumeicon			# system tray volume control
	network-manager-applet		# GUI / system tray network manager control
	udiskie				# disk automounter
	feh				# image viewer 
	betterlockscreen		# screen locker
	scrot				# screenshot utility
	xautolock			# automatic locking utility
	cbatticon			# battery system tray icon
	diff-so-fancy			# diff pager
	gruvbox-dark-gtk		# gtk gruvbox theme
	gruvbox-dark-icons-gtk		# gtk gruvbox icons
	lxappearance			# theme switcher
	starship			# shell prompt
	nerd-fonts-source-code-pro	# shell prompt icons
	ttf-font-awesome		# font icons
	jq				# json helper
	wget				# request sending helper
)

yay -Syu --needed "${pkgs[@]}"

if [[ ! -d "$HOME/Pictures/screenshots" ]]; then
	mkdir "$HOME/Pictures/screenshots"
fi
