#!/bin/bash

pkgs=(
	vim				# editor
	beets				# music organiser
	dunst				# notification manager
	i3-wm				# tilling window manager
	polybar				# status bar
	cmus				# music player
	rofi				# dmenu replacement
	alacritty			# terminal emulator
	picom				# compositor
	nnn				# terminal file manager
	adobe-source-code-pro-fonts	# main font
	network-manager-applet		# GUI / system tray network manager control
	udiskie				# disk automounter
	feh				# image viewer 
	betterlockscreen		# screen locker
	scrot				# screenshot utility
	xautolock			# automatic locking utility
	cbatticon			# battery system tray icon
	diff-so-fancy			# diff pager
	gruvbox-dark-gtk		# gtk gruvbox theme
	gruvbox-dark-icons-gtk		# gtk gruvbox icons
	lxappearance			# theme switcher
	starship			# shell prompt
	nerd-fonts-source-code-pro	# shell prompt icons
	ttf-font-awesome		# font icons
	noto-fonts-emoji		# emoji font
	wget				# request sending helper
	pulseaudio			# sound server
	pulseaudio-alsa			# sound server integration with alsa
	pavucontrol			# volume control
	pasystray			# system tray volume control
	pacman-contrib			# pacman helpers
	tldr				# cmd cheatsheets
	bash-completion			# completion funcs for bash
	youtube-dl			# youtube downloader
	httpie				# http client
	websocat			# websocket client
)

yay -Syu --needed "${pkgs[@]}"

if [[ ! -d "$HOME/Pictures/screenshots" ]]; then
	mkdir -p "$HOME/Pictures/screenshots"
fi

if [[ ! -f "/etc/udev/rules.d/95-battery.rules" ]]; then
	sudo cp "$(chezmoi source-path)/.sysconf/95-battery.rules" /etc/udev/rules.d/95-battery.rules
fi
