#!/bin/bash

updates_arch="$(checkupdates 2> /dev/null | wc -l )"
updates_aur="$(yay -Qum 2> /dev/null | wc -l)"
updates=$(("$updates_arch" + "$updates_aur"))

if (( "$updates" > 0 )); then
	echo "%{F#cc241d}%{F-} Official: $updates_arch AUR: $updates_aur"
	exit
fi

echo %{F#b8bb26}%{F-}
