[battery]
disabled = true

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[directory]
truncation_length = 2
truncate_to_repo = false
read_only = " "

[golang]
format = "using [Go ($version )]($style)"

[java]
format = "using [Java ($version )]($style)"

[python]
format = "using [Kotlin ($version )]($style)"

[rust]
format = "using [Rust ($version )]($style)"
